name: Test Schedule

on:
  schedule:
    - cron: '0 2 * * *'  # Every 2 AM 
  workflow_dispatch:       # Allows manual run from the UI

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello! This ran on a schedule."
